### ISSUE TITLE
SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by hanssens** [tgardner/appbuilder-convert#1]
After installing the tool through NPM, I get an exception after running the following command:

```
appbuilder-convert --source MyTestApp/ --dest Cordova/
```

Of course, the .abproject file resides in the MyTestApp folder.

The exception:

```
/usr/local/lib/node_modules/appbuilder-convert/node_modules/gitignore-parser/lib/index.js:76
      item[0].length > 0 ? new RegExp('^((' + item[0].join(')|(') + '))') : ne
                                                                  ^
SyntaxError: Invalid regular expression: /^((([^\/]+)\.abproject)|(([^\/]+)\/(.+)\/\.DS_Store)|(([^\/]+)\/(.+)\/Thumbs\.db)|(([^\/]+)\/(.+)\/__MACOSX\/**\/*)|(\.ab\/)|(\.ab\/(.+)\/([^\/]+))|(\.abignore)|(\.abignore)|(\.abproject)|(\.git\/(.+)\/([^\/]+))|(\.gitignore)|(App_Resources\/)|(Plugins\/)|(bin\/(.+)\/([^\/]+))|(cordova([^\/]+))|(obj\/(.+)\/([^\/]+)))/: Nothing to repeat
    at new RegExp (native)
    at /usr/local/lib/node_modules/appbuilder-convert/node_modules/gitignore-parser/lib/index.js:76:67
    at Array.map (native)
    at Object.exports.parse (/usr/local/lib/node_modules/appbuilder-convert/node_modules/gitignore-parser/lib/index.js:74:4)
    at Object.exports.compile (/usr/local/lib/node_modules/appbuilder-convert/node_modules/gitignore-parser/lib/index.js:12:24)
    at CopyAssetsTaskFactory (/usr/local/lib/node_modules/appbuilder-convert/lib/tasks/assets.js:22:27)
    at ConverterFactory (/usr/local/lib/node_modules/appbuilder-convert/lib/converter.js:71:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/appbuilder-convert/index.js:34:43)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

I'm running Mac OSX 10.10.3, with an AppBuilder project created with the Visual Studio Extension.

**Comment by tgardner** [comment]
Hi @hanssens,

Do you have an invalid syntax in your `MyTestApp/.abignore` file?

Thanks,

Trent

**Comment by hanssens** [comment]
Not necessarily invalid syntax, but I do have the following:

```
# Windows files
*/**/Thumbs.db

# Mac OS files
*/**/.DS_Store
*/**/__MACOSX/**/*

# Visual Studio files
bin/**/*
obj/**/*

# Source control files
.gitignore
.git/**/*

# AppBuilder files
.abignore
.ab/**/*
```

This is the auto-generated file by AppBuilder itself through the VS Extensions on a Windows virtual machine. If I remove the forward slashes entirely, the error is gone as well.

So, possibly either the gitignore-parser should escape the regular expression by doubling the slashes, or the task in this project should?
